versions:
    list:
        - 0.16.0
    stable: 0.16.0
build:
    - version: '*'
      source:
        - https://github.com/google/highway/archive/refs/tags/${PV}.tar.gz -> ${P}.tar.gz
      engine: cmake
      arguments:
        - -DHWY_SYSTEM_GTEST=ON
        - -DBUILD_TESTING=OFF
files:
    highway-0.16.0.tar.gz:
        size: 1639388
        hashes:
            sha1: d1a5b225370ac583dbe2723c32f5465a8d561cd6
            sha3-256: 230a1ccd2f0aebd3f82e267d8d8b2f9b23e24bd0f905a0a26c4a484271c3843c
            sha256: 746c9578446be6c5286e8846c5f0d4118c0c1f04219c401abadcb8a5f2051893
