versions:
    list:
        - 1.9.3
    stable: 1.9.3
build:
    - version: '*'
      env:
        - CMAKE_ROOT=${S}/build/cmake
      source:
        - https://github.com/lz4/lz4/archive/v${PV}.tar.gz
      engine: cmake
files:
    v1.9.3.tar.gz:
        size: 320958
        hashes:
            sha1: 5a19554ef404a609123b756ddcbbb677df838f05
            sha3-256: 7bf25eb6614b68b3983d86317682f1574bb3ecdcc91200b6ce6d23aae0a6deca
            sha256: 030644df4611007ff7dc962d981f390361e6c97a34e5cbc393ddfbe019ffe2c1
