versions:
    list:
        - 0.1.5
    stable: 0.1.5
build:
    - version: '*'
      source:
        - https://github.com/KarpelesLab/${PN}/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
      engine: none
      compile_post:
        - make CC=musl-gcc
      install_post:
        - make install PREFIX="/pkg/main/${PKG}.core.${PVRF}" DESTDIR="${D}"
