versions:
    list:
        - 4.8.0
    stable: 4.8.0
build:
    - version: '*'
      import:
        - tinfo
        - libxcrypt
      source:
        - https://ftp.gnu.org/gnu/${PN}/${P}.tar.gz
      engine: autoconf
      options: [build_in_tree]
      arguments:
        - --with-socket-dir=/var/run/screen
        - --with-pty-group=5
        - --with-sys-screenrc=/etc/screenrc
      configure_post:
        - sed -i -e "s%/usr/local/etc/screenrc%/etc/screenrc%" {etc,doc}/*
files:
    screen-4.8.0.tar.gz:
        size: 854854
        hashes:
            sha1: 2328927e10e68d357bdfec7bd740726011e834e9
            sha3-256: 9e60c78ee7b0f51f8480e50542e3a56d33195d2b77a453a4fa1e4ec1be82e977
            sha256: 6e11b13d8489925fde25dfb0935bf6ed71f9eb47eff233a181e078fde5655aa1
